"""Deprecated compatibility exports for former ``application.legacy`` users.

Native command definitions live in ``peerhub.application.commands`` by domain.
This module remains for known external imports during the migration.
"""

from peerhub.application import compatibility as _compatibility
from peerhub.application.commands import (
    Command as Command,
    SubmissionMetadata as SubmissionMetadata,
)
from peerhub.application.commands import sessions as _sessions_commands
from peerhub.application.commands import rooms as _rooms_commands
from peerhub.application.commands import leadership as _leadership_commands
from peerhub.application.commands import duty as _duty_commands
from peerhub.application.commands import tasks as _tasks_commands
from peerhub.application.commands import lessons as _lessons_commands
from peerhub.application.commands import consensus as _consensus_commands
from peerhub.application.commands import alerts as _alerts_commands
from peerhub.application.commands import peers as _peers_commands
from peerhub.application.commands import health as _health_commands
from peerhub.application.commands import leases as _leases_commands
from peerhub.application.commands import effects as _effects_commands
from peerhub.application.commands import roles as _roles_commands
from peerhub.application.commands import artifacts as _artifacts_commands
from peerhub.application.commands import locks as _locks_commands
from peerhub.application.commands import feedback as _feedback_commands
from peerhub.application.commands import operational_errors as _operational_errors_commands
from peerhub.application.commands import dispatch as _dispatch_commands


SessionOpenCommand = _sessions_commands.SessionOpenCommand
SessionCloseCommand = _sessions_commands.SessionCloseCommand
SessionHeartbeatCommand = _sessions_commands.SessionHeartbeatCommand
StatusReadCommand = _rooms_commands.StatusReadCommand
UpdateStatusCommand = _rooms_commands.UpdateStatusCommand
NewTopicCommand = _rooms_commands.NewTopicCommand
ThreadNewCommand = _rooms_commands.ThreadNewCommand
ThreadAppendCommand = _rooms_commands.ThreadAppendCommand
MessageSendCommand = _rooms_commands.MessageSendCommand
RoomBroadcastCommand = _rooms_commands.RoomBroadcastCommand
MessageCheckCommand = _rooms_commands.MessageCheckCommand
MessageMarkReadCommand = _rooms_commands.MessageMarkReadCommand
ThreadPromoteCommand = _rooms_commands.ThreadPromoteCommand
AppendHandoffCommand = _rooms_commands.AppendHandoffCommand
ContinuityCheckpointCommand = _rooms_commands.ContinuityCheckpointCommand
ContextFillCommand = _rooms_commands.ContextFillCommand
ThreadReactCommand = _rooms_commands.ThreadReactCommand
ClearRoomCommand = _rooms_commands.ClearRoomCommand
RoomStatusCommand = _rooms_commands.RoomStatusCommand
LeaderClaimCommand = _leadership_commands.LeaderClaimCommand
DiscoverCandidatesCommand = _leadership_commands.DiscoverCandidatesCommand
ElectLeaderCommand = _leadership_commands.ElectLeaderCommand
LeaderYieldCommand = _leadership_commands.LeaderYieldCommand
TerminalHandoffCommand = _duty_commands.TerminalHandoffCommand
TerminalClaimCommand = _duty_commands.TerminalClaimCommand
TerminalHeartbeatCommand = _duty_commands.TerminalHeartbeatCommand
TerminalCloseCommand = _duty_commands.TerminalCloseCommand
TerminalDutySweepCommand = _duty_commands.TerminalDutySweepCommand
TaskCreateCommand = _tasks_commands.TaskCreateCommand
TaskClaimStartCommand = _tasks_commands.TaskClaimStartCommand
TaskCheckpointCommand = _tasks_commands.TaskCheckpointCommand
TaskCompleteCommand = _tasks_commands.TaskCompleteCommand
TaskFailCommand = _tasks_commands.TaskFailCommand
TaskCancelCommand = _tasks_commands.TaskCancelCommand
TaskStatusCommand = _tasks_commands.TaskStatusCommand
TaskFailoverCommand = _tasks_commands.TaskFailoverCommand
ApprovalRequestCommand = _tasks_commands.ApprovalRequestCommand
LessonInjectCommand = _lessons_commands.LessonInjectCommand
LessonProposeCommand = _lessons_commands.LessonProposeCommand
LessonActivateCommand = _lessons_commands.LessonActivateCommand
LessonRetireCommand = _lessons_commands.LessonRetireCommand
LessonBroadcastCommand = _lessons_commands.LessonBroadcastCommand
LessonsListCommand = _lessons_commands.LessonsListCommand
ProposalAddCommand = _consensus_commands.ProposalAddCommand
ProposalVoteCommand = _consensus_commands.ProposalVoteCommand
ProposalListCommand = _consensus_commands.ProposalListCommand
ArbiterReviewCommand = _consensus_commands.ArbiterReviewCommand
AlertRaiseCommand = _alerts_commands.AlertRaiseCommand
RegisterNodeCommand = _peers_commands.RegisterNodeCommand
ListNodesCommand = _peers_commands.ListNodesCommand
BindProfileCommand = _peers_commands.BindProfileCommand
ModelStatusCommand = _peers_commands.ModelStatusCommand
PeerStatusCommand = _peers_commands.PeerStatusCommand
HealthCheckCommand = _health_commands.HealthCheckCommand
PeerQuarantineCommand = _health_commands.PeerQuarantineCommand
PeerRecoverCommand = _health_commands.PeerRecoverCommand
HealthPrecheckCommand = _health_commands.HealthPrecheckCommand
CheckGateCommand = _health_commands.CheckGateCommand
HealthSweepCommand = _health_commands.HealthSweepCommand
LeaseStatusCommand = _leases_commands.LeaseStatusCommand
LeaseSweepCommand = _leases_commands.LeaseSweepCommand
EffectStatusCommand = _effects_commands.EffectStatusCommand
AssignRoleCommand = _roles_commands.AssignRoleCommand
ReleaseRoleCommand = _roles_commands.ReleaseRoleCommand
RoleStatusCommand = _roles_commands.RoleStatusCommand
ArtifactClaimCommand = _artifacts_commands.ArtifactClaimCommand
ArtifactStatusCommand = _artifacts_commands.ArtifactStatusCommand
ArtifactFinalizeCommand = _artifacts_commands.ArtifactFinalizeCommand
LockAcquireCommand = _locks_commands.LockAcquireCommand
LockReleaseCommand = _locks_commands.LockReleaseCommand
LockStatusCommand = _locks_commands.LockStatusCommand
FeedbackAddCommand = _feedback_commands.FeedbackAddCommand
FeedbackListCommand = _feedback_commands.FeedbackListCommand
FeedbackResolveCommand = _feedback_commands.FeedbackResolveCommand
ReportErrorCommand = _operational_errors_commands.ReportErrorCommand
ResolveQuarantineReviewCommand = (
    _operational_errors_commands.ResolveQuarantineReviewCommand
)
ConsensusCheckCommand = _consensus_commands.ConsensusCheckCommand
ConsensusProposeCommand = _consensus_commands.ConsensusProposeCommand
ConsensusSweepCommand = _consensus_commands.ConsensusSweepCommand
ConsensusVoteCommand = _consensus_commands.ConsensusVoteCommand
SubmitCoordinatorDispatch = _dispatch_commands.SubmitCoordinatorDispatch
SubmitDispatch = _dispatch_commands.SubmitDispatch
SubmitManyDispatch = _dispatch_commands.SubmitManyDispatch
legacy_room_id = _compatibility.legacy_room_id
legacy_thread_slug = _compatibility.legacy_thread_slug
